import type { Config } from "tailwindcss";

export default {
  darkMode: ["class"],
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        chart: {
          "1": "hsl(var(--chart-1))",
          "2": "hsl(var(--chart-2))",
          "3": "hsl(var(--chart-3))",
          "4": "hsl(var(--chart-4))",
          "5": "hsl(var(--chart-5))",
        },
        saffron: {
          DEFAULT: "#e6c229",
          100: "#302906",
          200: "#61510b",
          300: "#917a11",
          400: "#c2a217",
          500: "#e6c229",
          600: "#ebcf53",
          700: "#f0db7e",
          800: "#f5e7a9",
          900: "#faf3d4",
        },
        pumpkin_spice: {
          DEFAULT: "#f17105",
          100: "#301601",
          200: "#602c02",
          300: "#904203",
          400: "#c05904",
          500: "#f17105",
          600: "#fb8b2f",
          700: "#fca863",
          800: "#fdc597",
          900: "#fee2cb",
        },
        intense_cherry: {
          DEFAULT: "#d11149",
          100: "#2a030e",
          200: "#53071c",
          300: "#7d0a2b",
          400: "#a60d39",
          500: "#d11149",
          600: "#ee2c63",
          700: "#f2608a",
          800: "#f695b1",
          900: "#fbcad8",
        },
        electric_indigo: {
          DEFAULT: "#6610f2",
          100: "#150331",
          200: "#290563",
          300: "#3e0894",
          400: "#520ac6",
          500: "#6610f2",
          600: "#8641f5",
          700: "#a471f8",
          800: "#c3a0fa",
          900: "#e1d0fd",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
} satisfies Config;
